### ISSUE TITLE
Formats of moves don't match between OrganismTree and OrganismTurn

### ISSUE THREAD

**Issue by ggsun** [prismofeverything/organism#4]
The formats of EAT and GROW moves returned by OrganismTree are not compatible with OrganismTurn. For the EAT moves, the order of from_space and to_space appears to be flipped. For the GROW moves, OrganismTree does not return `push_food_space`, while OrganismTurn requires this to be specified (I thought you made the decision to just remove the food in the space that an element grew into if I remember correctly). The format of the `consume_food` element in GROW moves is also different between what OrganismTree returns and what OrganismTurn expects.

**Comment by prismofeverything** [comment]
Oh nice, good catch! I believe I updated the rule in one place but not the other, I'll fix that.

**Comment by prismofeverything** [comment]
Okay, made the updates here: https://github.com/prismofeverything/organism/pull/3/commits/ea7710347a282a61499f555e37063d0e329ae7d6

* Between OTree and OTurn I just removed the requirement for `push_food_space` from OTurn, which is how it should work (in general OTree was correct and OTurn was out of date). 
* `from_space` and `to_space` became `food_space` and `eat_space` so that my natural source-->destination ordering doesn't take over the larger consistency of having the space where the element actually doing the action resides come first in the action list. 
* The format for what spaces the food for growth comes from was a dictionary on one hand and pure tuples on the other. This is because the value is naturally a dictionary, but the format generated by OTree is immutable (a tuple) reflecting dictionary structure. I like the immutability of using tuples more than I like the flexibility of using a dictionary for this so I'm going with the nested tuple here. 

Thanks for pointing these out! Excited to see this in action.
